name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ./Entatea/Entatea.sln
    - name: Build Entatea
      run: dotnet build ./Entatea/Entatea.sln --configuration Release --no-restore
    - name: Pack Entatea
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release ./Entatea/Entatea/Entatea.csproj
    - name: Pack InMemory
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release ./Entatea/Entatea.InMemory/Entatea.InMemory.csproj
    - name: Pack SQL Server
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release ./Entatea/Entatea.SqlServer/Entatea.SqlServer.csproj
    - name: Pack My SQL
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release ./Entatea/Entatea.MySql/Entatea.MySql.csproj
    - name: Pack SQLite
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release ./Entatea/Entatea.Sqlite/Entatea.Sqlite.csproj
    - name: Publish NuGet
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
